services:
    feedback-voting-database:
        container_name: feedback-voting-database
        build:
            dockerfile: Dockerfile.database
            context: .
        environment:
            - POSTGRES_PASSWORD=0987654321
            - POSTGRES_USER=postgres
        # volumes:
        #     - feedback-voting-database-volume:/var/lib/postgresql/data
        ports:
            - 5432:5432

# volumes:
#     feedback-voting-database-volume:
#         driver: local
#         driver_opts:
#             o: bind
#             type: none
#             device: ./.database
