services:
    feedback-voting-database:
        container_name: feedback-voting-database
        build:
            dockerfile: Dockerfile.database
            context: .
        environment:
            - POSTGRES_PASSWORD=0987654321
            - POSTGRES_USER=postgres
        ports:
            - 55432:5432

    feedback-voting-web-api:
        container_name: feedback-voting-web-api
        build:
            dockerfile: Dockerfile.web-api
            context: .
        ports:
          - 3000:3000
        depends_on:
            - feedback-voting-database
        restart: always
        command: sh -c "npx prisma migrate deploy && npx prisma db seed && node ./src/app.js"